name: reporting_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # flutter_localizations:
  #   sdk: flutter
  firebase_database: ^10.4.9
  firebase_core: ^2.27.0
  http: ^1.2.0
  image_picker: ^1.0.7
  flutter_linkify: ^6.0.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/

fonts:
  - family: Montserrat
    fonts:
      - asset: fonts/Montserrat-VariableFont_wght.ttf
