// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVHcYjEvUbUA-bEGOxAd6YLx_V1hpZLfQ',
    appId: '1:766336888260:web:c62acc97c682af539b4891',
    messagingSenderId: '766336888260',
    projectId: 'dashboard-data-6670c',
    authDomain: 'dashboard-data-6670c.firebaseapp.com',
    databaseURL: 'https://dashboard-data-6670c-default-rtdb.firebaseio.com',
    storageBucket: 'dashboard-data-6670c.appspot.com',
    measurementId: 'G-VZ8486LQT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQiV1ZEGSvJ6PRSoABmpjBxKvOzwn-xAs',
    appId: '1:766336888260:android:7d0c4a8f7dfcbd099b4891',
    messagingSenderId: '766336888260',
    projectId: 'dashboard-data-6670c',
    databaseURL: 'https://dashboard-data-6670c-default-rtdb.firebaseio.com',
    storageBucket: 'dashboard-data-6670c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4vrG6Cf62XHgQ1NUxCRZN85TC8RjOPO4',
    appId: '1:766336888260:ios:ec545d54127b35389b4891',
    messagingSenderId: '766336888260',
    projectId: 'dashboard-data-6670c',
    databaseURL: 'https://dashboard-data-6670c-default-rtdb.firebaseio.com',
    storageBucket: 'dashboard-data-6670c.appspot.com',
    iosClientId: '766336888260-ugck468lqtm5jeh9hlskm36r2e04p905.apps.googleusercontent.com',
    iosBundleId: 'com.example.reportingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4vrG6Cf62XHgQ1NUxCRZN85TC8RjOPO4',
    appId: '1:766336888260:ios:9136b3e1eeb2c3899b4891',
    messagingSenderId: '766336888260',
    projectId: 'dashboard-data-6670c',
    databaseURL: 'https://dashboard-data-6670c-default-rtdb.firebaseio.com',
    storageBucket: 'dashboard-data-6670c.appspot.com',
    iosClientId: '766336888260-8a9f6pg3dp93d09ms4u319npf6bj2g46.apps.googleusercontent.com',
    iosBundleId: 'com.example.reportingApp.RunnerTests',
  );
}
